### ISSUE TITLE
Has this idea died before implentation?

### ISSUE THREAD

**Issue by danblade** [Bamimore-Tomi/go-templates-guide#1]
Oluwatomisin,

Your post, https://blog.logrocket.com/using-golang-templates/, was very helpful. 
This repository, however, is not yet helpful. 

Is this project something that you just need a little help with or is it dead and buried?

**Comment by Bamimore-Tomi** [comment]
Hi @danblade , I think I need to update the readme. The repository is only meant to house all the code snippets in the article. So I put them in separate [branches](https://github.com/Bamimore-Tomi/go-templates-guide/branches).

I'll merge the last branch into the main, so the repository does not look empty.

I am also open to any help with improving it.

**Comment by danblade** [comment]
Thank you!

Obviously I am new and did not find the branches.
